-- 코드를 입력하세요
SELECT T.AUTHOR_ID,
       T.AUTHOR_NAME,
       T.CATEGORY,
       SUM(T.TOTAL_SALES) AS TOTAL_SALES
  FROM (
SELECT B.AUTHOR_ID,
       B.AUTHOR_NAME,
       A.CATEGORY,
       C.SALES * A.PRICE AS TOTAL_SALES
  FROM BOOK A, AUTHOR B, BOOK_SALES C
 WHERE A.BOOK_ID = C.BOOK_ID
   AND B.AUTHOR_ID = A.AUTHOR_ID
   AND C.SALES_DATE >= TO_DATE('202201', 'YYYYMM')
   AND C.SALES_DATE < TO_DATE('202202', 'YYYYMM')) T
 GROUP BY T.AUTHOR_ID,
          T.AUTHOR_NAME,
          T.CATEGORY
 ORDER BY 1, 3 DESC